import React, { createContext, useContext, useState, useEffect } from 'react';
const translations = {
    fr: {
        // Navigation
        'nav.home': 'Accueil',
        'nav.login': 'Connexion',
        'nav.register': 'Inscription',
        'nav.logout': 'Déconnexion',
        'nav.dashboard': 'Tableau de bord',
        // Home Page
        'home.hero.title': 'Trouvez un mécanicien près de chez vous',
        'home.hero.subtitle': 'La plateforme qui connecte les automobilistes avec des mécaniciens qualifiés',
        'home.search.placeholder': 'Entrez votre ville ou votre adresse...',
        'home.search.button': 'Rechercher un mécanicien',
        'home.cta.button': 'Demander un mécanicien',
        'home.howItWorks.title': 'Comment ça marche ?',
        'home.step1.title': 'Recherchez',
        'home.step1.desc': 'Trouvez des mécaniciens qualifiés près de chez vous',
        'home.step2.title': 'Demandez',
        'home.step2.desc': 'Envoyez une demande de service en quelques clics',
        'home.step3.title': 'Recevez de l\'aide',
        'home.step3.desc': 'Le mécanicien vient à vous et résout votre problème',
        'home.mechanics.title': 'Vous êtes mécanicien ?',
        'home.mechanics.subtitle': 'Rejoignez notre plateforme et développez votre activité',
        'home.mechanics.benefit1': 'Accès à des milliers de clients',
        'home.mechanics.benefit2': 'Gestion simple des demandes',
        'home.mechanics.benefit3': 'Paiements sécurisés',
        'home.mechanics.subscription': 'Abonnement : 200 MAD/mois',
        'home.mechanics.button': 'Rejoindre maintenant',
        // Stats
        'home.stats.mechanics': 'Mécaniciens',
        'home.stats.clients': 'Clients',
        'home.stats.interventions': 'Interventions',
        'home.stats.rating': 'Note moyenne',
        // Testimonials
        'home.testimonials.title': 'Ce que disent nos clients',
        'home.testimonials.1.name': 'Ahmed Benali',
        'home.testimonials.1.role': 'Client Satisfait',
        'home.testimonials.1.text': 'Service rapide et professionnel. Le mécanicien est arrivé en 20 minutes !',
        'home.testimonials.2.name': 'Sarah Idrissi',
        'home.testimonials.2.role': 'Conductrice',
        'home.testimonials.2.text': 'Très pratique quand on tombe en panne au milieu de nulle part. Je recommande.',
        'home.testimonials.3.name': 'Karim Tazi',
        'home.testimonials.3.role': 'Client',
        'home.testimonials.3.text': 'Transparence totale sur les prix et qualité de service irréprochable.',
        // Global Features
        'home.features.title': 'Pourquoi nous choisir ?',
        'home.features.1.title': 'Disponibilité 24/7',
        'home.features.1.desc': 'Nos mécaniciens sont disponibles à tout moment pour vous aider.',
        'home.features.2.title': 'Prix Garantis',
        'home.features.2.desc': 'Pas de surprise, les tarifs sont fixés à l\'avance.',
        'home.features.3.title': 'Professionnels Vérifiés',
        'home.features.3.desc': 'Tous nos mécaniciens sont certifiés et évalués.',
        // FAQ
        'home.faq.title': 'Questions Fréquentes',
        'home.faq.1.q': 'Combien coûte une intervention ?',
        'home.faq.1.a': 'Le prix dépend du type de panne et de la distance. Un devis vous est proposé avant validation.',
        'home.faq.2.q': 'Comment payer ?',
        'home.faq.2.a': 'Vous pouvez payer en espèces directement au mécanicien ou via l\'application.',
        'home.faq.3.q': 'Les pièces de rechange sont-elles incluses ?',
        'home.faq.3.a': 'Non, le prix inclut uniquement la main d\'œuvre et le déplacement. Les pièces sont à votre charge.',
        // Footer
        'footer.about': 'À propos',
        'footer.contact': 'Contact',
        'footer.terms': 'Conditions d\'utilisation',
        'footer.privacy': 'Confidentialité',
        'footer.email': 'contact@allomecanique.ma',
        'footer.phone': '+212 5XX-XXXXXX',
        'footer.rights': '© 2026 Allo Mécanique. Tous droits réservés.',
        // Login
        'login.title': 'Connexion',
        'login.email': 'Email',
        'login.password': 'Mot de passe',
        'login.button': 'Se connecter',
        'login.noAccount': 'Pas de compte ?',
        'login.register': 'Inscrivez-vous',
        'login.asClient': 'En tant que client',
        'login.asMechanic': 'En tant que mécanicien',
        'login.asAdmin': 'En tant qu\'admin',
        // Registration
        'register.title': 'Inscription',
        'register.clientTitle': 'Inscription Client',
        'register.mechanicTitle': 'Inscription Mécanicien',
        'register.name': 'Nom complet',
        'register.email': 'Email',
        'register.phone': 'Téléphone',
        'register.password': 'Mot de passe',
        'register.confirmPassword': 'Confirmer le mot de passe',
        'register.city': 'Ville',
        'register.address': 'Adresse',
        'register.specialty': 'Spécialité',
        'register.experience': 'Années d\'expérience',
        'register.button': 'S\'inscrire',
        'register.haveAccount': 'Déjà un compte ?',
        'register.login': 'Connectez-vous',
        'register.asClient': 'Inscription Client',
        'register.asMechanic': 'Inscription Mécanicien',
        'register.subscriptionNote': 'Abonnement mensuel requis : 200 MAD',
        // Client Dashboard
        'client.title': 'Tableau de bord Client',
        'client.welcome': 'Bienvenue',
        'client.requestMechanic': 'Demander un mécanicien',
        'client.myRequests': 'Mes demandes',
        'client.nearbyMechanics': 'Mécaniciens à proximité',
        'client.notifications': 'Notifications',
        'client.profile': 'Mon profil',
        'client.request.title': 'Nouvelle demande',
        'client.request.problem': 'Décrivez votre problème',
        'client.request.location': 'Localisation',
        'client.request.submit': 'Envoyer la demande',
        'client.status.pending': 'En attente',
        'client.status.accepted': 'Acceptée',
        'client.status.completed': 'Terminée',
        'client.status.rejected': 'Refusée',
        'client.rating': 'Note',
        'client.distance': 'km',
        'client.available': 'Disponible',
        // Mechanic Dashboard
        'mechanic.title': 'Tableau de bord Mécanicien',
        'mechanic.welcome': 'Bienvenue',
        'mechanic.subscription': 'Abonnement',
        'mechanic.subscriptionStatus': 'Statut d\'abonnement',
        'mechanic.active': 'Actif',
        'mechanic.inactive': 'Inactif',
        'mechanic.paySubscription': 'Payer l\'abonnement',
        'mechanic.nextPayment': 'Prochain paiement',
        'mechanic.requests': 'Demandes de service',
        'mechanic.availability': 'Disponibilité',
        'mechanic.earnings': 'Revenus',
        'mechanic.profile': 'Mon profil',
        'mechanic.accept': 'Accepter',
        'mechanic.reject': 'Refuser',
        'mechanic.complete': 'Terminer',
        'mechanic.thisMonth': 'Ce mois',
        'mechanic.totalRequests': 'Demandes totales',
        'mechanic.subscriptionWarning': 'Votre abonnement expire bientôt. Renouvelez pour rester actif.',
        // Admin Dashboard
        'admin.title': 'Tableau de bord Admin',
        'admin.welcome': 'Bienvenue Admin',
        'admin.statistics': 'Statistiques',
        'admin.totalClients': 'Total Clients',
        'admin.totalMechanics': 'Total Mécaniciens',
        'admin.activeRequests': 'Demandes actives',
        'admin.monthlyRevenue': 'Revenus mensuels',
        'admin.manageClients': 'Gérer les clients',
        'admin.manageMechanics': 'Gérer les mécaniciens',
        'admin.payments': 'Paiements',
        'admin.deactivate': 'Désactiver',
        'admin.delete': 'Supprimer',
        'admin.activate': 'Activer',
        'admin.view': 'Voir',
        'admin.subscriptionPaid': 'Payé',
        'admin.subscriptionUnpaid': 'Non payé',
        'admin.subscriptionExpired': 'Expiré',
        'admin.actions': 'Actions',
        'admin.status': 'Statut',
        'admin.name': 'Nom',
        'admin.email': 'Email',
        'admin.phone': 'Téléphone',
        'admin.city': 'Ville',
        'admin.subscription': 'Abonnement',
    },
    ar: {
        // Navigation
        'nav.home': 'الرئيسية',
        'nav.login': 'تسجيل الدخول',
        'nav.register': 'التسجيل',
        'nav.logout': 'تسجيل الخروج',
        'nav.dashboard': 'لوحة القيادة',
        // Home Page
        'home.hero.title': 'اعثر على ميكانيكي بالقرب منك',
        'home.hero.subtitle': 'المنصة التي تربط أصحاب السيارات بالميكانيكيين المؤهلين',
        'home.search.placeholder': 'أدخل مدينتك أو عنوانك...',
        'home.search.button': 'ابحث عن ميكانيكي',
        'home.cta.button': 'اطلب ميكانيكي',
        'home.howItWorks.title': 'كيف يعمل؟',
        'home.step1.title': 'ابحث',
        'home.step1.desc': 'اعثر على ميكانيكيين مؤهلين بالقرب منك',
        'home.step2.title': 'اطلب',
        'home.step2.desc': 'أرسل طلب خدمة ببضع نقرات',
        'home.step3.title': 'احصل على المساعدة',
        'home.step3.desc': 'الميكانيكي يأتي إليك ويحل مشكلتك',
        'home.mechanics.title': 'هل أنت ميكانيكي؟',
        'home.mechanics.subtitle': 'انضم إلى منصتنا ونمِّ نشاطك',
        'home.mechanics.benefit1': 'الوصول إلى آلاف العملاء',
        'home.mechanics.benefit2': 'إدارة بسيطة للطلبات',
        'home.mechanics.benefit3': 'مدفوعات آمنة',
        'home.mechanics.subscription': 'الاشتراك: 200 درهم/شهر',
        'home.mechanics.button': 'انضم الآن',
        // Stats
        'home.stats.mechanics': 'ميكانيكي',
        'home.stats.clients': 'عميل',
        'home.stats.interventions': 'تدخل',
        'home.stats.rating': 'معدل التقييم',
        // Testimonials
        'home.testimonials.title': 'ماذا يقول عملاؤنا',
        'home.testimonials.1.name': 'أحمد بنعلي',
        'home.testimonials.1.role': 'عميل راضٍ',
        'home.testimonials.1.text': 'خدمة سريعة ومهنية. وصل الميكانيكي في 20 دقيقة!',
        'home.testimonials.2.name': 'سارة الإدريسي',
        'home.testimonials.2.role': 'سائقة',
        'home.testimonials.2.text': 'مريح جداً عندما تتعطل السيارة في مكان معزول. أوصي به بشدة.',
        'home.testimonials.3.name': 'كريم التازي',
        'home.testimonials.3.role': 'عميل',
        'home.testimonials.3.text': 'شفافية تامة في الأسعار وجودة خدمة لا غبار عليها.',
        // Global Features
        'home.features.title': 'لماذا تختارنا؟',
        'home.features.1.title': 'توفر 24/7',
        'home.features.1.desc': 'ميكانيكيونا متاحون في أي وقت لمساعدتك.',
        'home.features.2.title': 'أسعار مضمونة',
        'home.features.2.desc': 'لا مفاجآت، يتم تحديد الأسعار مسبقاً.',
        'home.features.3.title': 'مهنيون معتمدون',
        'home.features.3.desc': 'جميع الميكانيكيين لدينا معتمدون وتم تقييمهم.',
        // FAQ
        'home.faq.title': 'أسئلة شائعة',
        'home.faq.1.q': 'كم تكلفة التدخل؟',
        'home.faq.1.a': 'يعتمد السعر على نوع العطل والمسافة. يتم تقديم عرض أسعار قبل التأكيد.',
        'home.faq.2.q': 'كيف يمكنني الدفع؟',
        'home.faq.2.a': 'يمكنك الدفع نقداً مباشرة للميكانيكي أو عبر التطبيق.',
        'home.faq.3.q': 'هل قطع الغيار مشمولة؟',
        'home.faq.3.a': 'لا، السعر يشمل فقط اليد العاملة والتنقل. قطع الغيار على نفقتك.',
        // Footer
        'footer.about': 'حول',
        'footer.contact': 'اتصل بنا',
        'footer.terms': 'شروط الاستخدام',
        'footer.privacy': 'الخصوصية',
        'footer.email': 'contact@allomecanique.ma',
        'footer.phone': '+212 5XX-XXXXXX',
        'footer.rights': '© 2026 ألو ميكانيك. جميع الحقوق محفوظة.',
        // Login
        'login.title': 'تسجيل الدخول',
        'login.email': 'البريد الإلكتروني',
        'login.password': 'كلمة المرور',
        'login.button': 'تسجيل الدخول',
        'login.noAccount': 'ليس لديك حساب؟',
        'login.register': 'سجل الآن',
        'login.asClient': 'كعميل',
        'login.asMechanic': 'كميكانيكي',
        'login.asAdmin': 'كمسؤول',
        // Registration
        'register.title': 'التسجيل',
        'register.clientTitle': 'تسجيل العميل',
        'register.mechanicTitle': 'تسجيل الميكانيكي',
        'register.name': 'الاسم الكامل',
        'register.email': 'البريد الإلكتروني',
        'register.phone': 'الهاتف',
        'register.password': 'كلمة المرور',
        'register.confirmPassword': 'تأكيد كلمة المرور',
        'register.city': 'المدينة',
        'register.address': 'العنوان',
        'register.specialty': 'التخصص',
        'register.experience': 'سنوات الخبرة',
        'register.button': 'سجل',
        'register.haveAccount': 'لديك حساب؟',
        'register.login': 'سجل الدخول',
        'register.asClient': 'تسجيل العميل',
        'register.asMechanic': 'تسجيل الميكانيكي',
        'register.subscriptionNote': 'الاشتراك الشهري المطلوب: 200 درهم',
        // Client Dashboard
        'client.title': 'لوحة قيادة العميل',
        'client.welcome': 'مرحباً',
        'client.requestMechanic': 'اطلب ميكانيكي',
        'client.myRequests': 'طلباتي',
        'client.nearbyMechanics': 'ميكانيكيون قريبون',
        'client.notifications': 'الإشعارات',
        'client.profile': 'ملفي الشخصي',
        'client.request.title': 'طلب جديد',
        'client.request.problem': 'صف مشكلتك',
        'client.request.location': 'الموقع',
        'client.request.submit': 'إرسال الطلب',
        'client.status.pending': 'قيد الانتظار',
        'client.status.accepted': 'مقبول',
        'client.status.completed': 'مكتمل',
        'client.status.rejected': 'مرفوض',
        'client.rating': 'التقييم',
        'client.distance': 'كم',
        'client.available': 'متاح',
        // Mechanic Dashboard
        'mechanic.title': 'لوحة قيادة الميكانيكي',
        'mechanic.welcome': 'مرحباً',
        'mechanic.subscription': 'الاشتراك',
        'mechanic.subscriptionStatus': 'حالة الاشتراك',
        'mechanic.active': 'نشط',
        'mechanic.inactive': 'غير نشط',
        'mechanic.paySubscription': 'ادفع الاشتراك',
        'mechanic.nextPayment': 'الدفع القادم',
        'mechanic.requests': 'طلبات الخدمة',
        'mechanic.availability': 'التوفر',
        'mechanic.earnings': 'الأرباح',
        'mechanic.profile': 'ملفي الشخصي',
        'mechanic.accept': 'قبول',
        'mechanic.reject': 'رفض',
        'mechanic.complete': 'إتمام',
        'mechanic.thisMonth': 'هذا الشهر',
        'mechanic.totalRequests': 'إجمالي الطلبات',
        'mechanic.subscriptionWarning': 'اشتراكك ينتهي قريباً. جدد للبقاء نشطاً.',
        // Admin Dashboard
        'admin.title': 'لوحة قيادة المسؤول',
        'admin.welcome': 'مرحباً المسؤول',
        'admin.statistics': 'الإحصائيات',
        'admin.totalClients': 'إجمالي العملاء',
        'admin.totalMechanics': 'إجمالي الميكانيكيين',
        'admin.activeRequests': 'الطلبات النشطة',
        'admin.monthlyRevenue': 'الإيرادات الشهرية',
        'admin.manageClients': 'إدارة العملاء',
        'admin.manageMechanics': 'إدارة الميكانيكيين',
        'admin.payments': 'المدفوعات',
        'admin.deactivate': 'تعطيل',
        'admin.delete': 'حذف',
        'admin.activate': 'تفعيل',
        'admin.view': 'عرض',
        'admin.subscriptionPaid': 'مدفوع',
        'admin.subscriptionUnpaid': 'غير مدفوع',
        'admin.subscriptionExpired': 'منتهي',
        'admin.actions': 'الإجراءات',
        'admin.status': 'الحالة',
        'admin.name': 'الاسم',
        'admin.email': 'البريد الإلكتروني',
        'admin.phone': 'الهاتف',
        'admin.city': 'المدينة',
        'admin.subscription': 'الاشتراك',
    },
};
const LanguageContext = createContext(undefined);
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('fr');
    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);
    const t = (key) => {
        return translations[language][key] || key;
    };
    return (<LanguageContext.Provider value={{ language, setLanguage, t }}>
        {children}
    </LanguageContext.Provider>);
};
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
